services:
#    alertnotification.example:
#        class: alert\notificationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
    notification.event.alert_email_listner.class: Alert\NotificationBundle\Listener\AlertEmailListener
    notification.event.alert_mailer.class: Alert\NotificationBundle\Listener\AlertMailer
    notification.event.alert_email_subscriber.class: Alert\NotificationBundle\Listener\AlertEmailSubscriber

services:
    notification.alert_mailer:
        class: %notification.event.alert_mailer.class%
        arguments: [@templating, @mailer, @router]

    notification.event.alert_email_listner:
        class: %notification.event.alert_email_listner.class%
        arguments: [@notification.alert_mailer, @service_container]
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: postPersist , priority: 100  }