<?php

namespace Alert\NotificationBundle\Repository;

/**
 * ObervedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservedRepository extends \Doctrine\ORM\EntityRepository
{
}
